//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotacionUCAWebApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        public int Id { get; set; }
        public int IdEstudiante { get; set; }
        public int IdVotacion { get; set; }
        public int VotosObtenidos { get; set; }
    }
}
