//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotacionUCAWebApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public int Id { get; set; }
        public string CodGrupo { get; set; }
        public string NombreCompleto { get; set; }
        public string NumCarnet { get; set; }
    }
}
